# Generated by Django 5.2.2 on 2025-06-27 16:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=300)),
                ("date", models.DateTimeField()),
                ("author", models.CharField(verbose_name=100)),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
    ]
