# Generated by Django 5.2.2 on 2025-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="image",
            field=models.FileField(
                default=None, max_length=240, null=True, upload_to="news_img/"
            ),
        ),
    ]
