# Generated by Django 5.2.2 on 2025-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
