# Generated by Django 5.2.2 on 2025-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blogs_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("life", "Lifestyle"),
                    ("edu", "Education"),
                    ("travel", "Travel"),
                    ("food", "Food"),
                    ("news", "News"),
                    ("finance", "Finance"),
                    ("health", "Health & Wellness"),
                    ("sports", "Sports"),
                    ("code", "Programming"),
                    ("art", "Art & Design"),
                    ("business", "Business"),
                    ("gaming", "Gaming"),
                    ("science", "Science"),
                    ("books", "Books & Literature"),
                    ("music", "Music"),
                    ("movies", "Movies & TV"),
                    ("personal", "Personal Development"),
                ],
                default=("tech", "technology"),
                max_length=20,
            ),
        ),
    ]
